// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDeviceBelong = "device_belong"

// DeviceBelong mapped from table <device_belong>
type DeviceBelong struct {
	UserID   int32 `gorm:"column:user_id;not null" json:"user_id"`
	DeviceID int32 `gorm:"column:device_id;not null" json:"device_id"`
}

// TableName DeviceBelong's table name
func (*DeviceBelong) TableName() string {
	return TableNameDeviceBelong
}
