// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDeviceInfo = "device_info"

// DeviceInfo mapped from table <device_info>
type DeviceInfo struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name     string `gorm:"column:name;not null" json:"name"`
	IP       string `gorm:"column:ip;not null" json:"ip"`
	Describe string `gorm:"column:describe" json:"describe"`
}

// TableName DeviceInfo's table name
func (*DeviceInfo) TableName() string {
	return TableNameDeviceInfo
}
